### PR TITLE
New website

### PR DESCRIPTION
**Pull request by SaraVieira**

### CODE REVIEW

**Comment by elizabetdev** [comment]
What if we create a section where girls can download resources to create codesandboxes. For instance:
* Logo
* Illustration A
* Illustration B
* Other things... Or not!

Then, they can share their creations on Twitter or do a PR to get featured on the website. 

The main purpose is to recognize all the girls in the React community! 

Also, during the conference, these creations should somehow be featured. 

What do you think, @SaraVieira?

**Comment by SaraVieira** [comment]
@miukimiu I think that is an amazing idea! How do envision that page to be?

Also should it be a contest? Because I am not sure it would be easy to pick

The featured part it can just the sandboxes on a screen and we make make that happen :D

**Comment by elizabetdev** [comment]
@SaraVieira it shouldn't be a contest. Just a showcase of works. Interactive art! 🎨

**Comment by SaraVieira** [comment]
But if it's not a contest then who wins? Everyone ? 🤔

**Pull request merged**
